#!/usr/bin/env python
import sys
import re

# Our test cases will always use the same dictionary file (with SHA1
# 6b898d7c48630be05b72b3ae07c5be6617f90d8e). Running `test/harness`
# will automatically download this dictionary for you if you don't
# have it already.

path = sys.argv[1] if len(sys.argv) >= 2 else '/usr/share/dict/words'

words = {}
for word in open(path).read().split("\n"):
    words[word] = word

for line in sys.stdin.readlines():
    output = []
    for word in re.findall(r"[^ \n]+", line):
        if word.lower() in words:
            output.append(word)
        else:
            output.append("<" + word + ">")
    print " ".join(output)
